### ISSUE TITLE
Failed to install insomnia-plugin-azure-ad-authentication

### ISSUE THREAD

**Issue by ChairmanMawh** [GillesZunino/insomnia-plugin-azure-ad-authentication#12]
I use Insomnia latest (9.1.1) but also tried on 2023.8xx and same result, I see this error when trying to install it, right after I hit the Install button:

> 
> Failed to install insomnia-plugin-azure-ad-authentication
> 
> There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub.](https://insomnia.rest/plugins)
> Additional Information
> Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}
> 
>     at IpcRenderer.invoke (node:electron/js2c/renderer_init:2:6995)
>     at async onSubmit (file:///C:/Users/ChairmanMawh/AppData/Local/insomnia/app-9.1.1/resources/app.asar/mainWindow-CPtKPVYi.js:1505:513)

**Comment by ChairmanMawh** [comment]
(I did an `npm init` and answered blank for all the questions, them did `npm install insomnia-plugin-azure-ad-authentication`, then moved it out of the node_modules folder and deleted the package/node_modules folders)

**Comment by GillesZunino** [comment]
Addressed in [1.1.2](https://github.com/GillesZunino/insomnia-plugin-azure-ad-authentication/releases/tag/v1.1.2)
