### ISSUE TITLE
URL Redirect error

### ISSUE THREAD

**Issue by HiqMustin** [GillesZunino/insomnia-plugin-azure-ad-authentication#15]
Hi

First of all great plug in! but it doesn't work for me :/

I get a "The redirect URI 'http://127.0.0.1/myapp' specified in the request does not match the redirect URIs configured for the application 'xxxxxxx'" error. 

I have provided all the details (entra global,tenantid,applicationid the scope) and also grant flow PKCE and token type "Access Token" but i fail to log in. I think there is some Entra sign in option missing because i can get a token through powershell script just fine.

I think it has to do with the code_challange & code_challange_method that is provided in the Powershell script but not in the plugin perhaps? and also scope ($tokenScopes) in the format of "api://xxxxxx/ .default" aswell as code_verifier ($pkceCodeVerifier).

This is part of the Powershell code used:

` $state = "xxxxx"
    $pkceCodeVerifier = "xxxx"
    $pkceCodeChallenge = "xx-xx"
    $entraIdLoginUri = "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/authorize"
    $redeemUri = "https://login.microsoftonline.com/$tenantID/oauth2/v2.0/token"
    
    Start-Process "$($entraIdLoginUri)?client_id=$applicationId&response_type=code&scope=$loginScopes&redirect_uri=$localHostRedirectUri&state=$state&code_challenge=$pkceCodeChallenge&code_challenge_method=S256"
    
    # Listen for redirect response on redirect uri
    $httpListener = New-Object System.Net.HttpListener
    $httpListener.Prefixes.Add("$localHostRedirectUri/")
    $httpListener.Start()
    $httpListenerContext = $httpListener.GetContext()
    $grantCode = $httpListenerContext.Request.QueryString["code"].ToString()
    $httpListenerResponse = $httpListenerContext.Response
    # Hold the HttpListener open until the login is complete and then send an info page
    
    # Exchange code for bearer token
    $body = @{
        tenant = $tenantId
        client_id = $applicationId
        response_type = "code"
        grant_type = "authorization_code"
        redirect_uri = $localHostRedirectUri
        scope = $tokenScopes
        state = $state
        code = $grantCode
        code_verifier = $pkceCodeVerifier
    }
    $response = Invoke-WebRequest -Method POST -Headers @{ Origin = $localHostRedirectUri } -Uri $redeemUri -body $body -ContentType 'application/x-www-form-urlencoded' | ConvertFrom-Json
    $bearerToken = $response.access_token
    
    # Create a redirect response to the original OAUTH2 redirect page through the HttpListener
    $responseHtml = [System.Text.Encoding]::UTF8.GetBytes("<!DOCTYPE html><html><body>Login successful - close page</body></html>")
    $httpListenerResponse.Close($responseHtml, $true)
    Start-Sleep -Seconds 2
    $httpListener.Stop()
    $httpListener.Close()
    
    return $bearerToken`

**Comment by GillesZunino** [comment]
This seems unrelated to the Entra ID plugin for Insomnia. For general Entra ID questions, I recommend you look at repos in the AzureAD github organization at https://github.com/AzureAD and choose the repo / which best matches your scenario or language or choice.

The code above seems to be related to Powershell - Perhaps this repo helps you: https://github.com/AzureAD/azure-activedirectory-powershell

**Comment by HiqMustin** [comment]
Hi

Sorry i didn't describe the issue clearly. The Powershell code is working and i get the token back without issues. Now i'm trying to get the token within Insomnia with help of this plug in but it fails. 

If i compare the information provided in the Powershell script there are some additional information that can't be entered in the plug in:

"I think it has to do with the code_challange & code_challange_method that is provided in the Powershell script but not in the plugin perhaps? and also scope ($tokenScopes) in the format of "api://xxxxxx/ .default" aswell as code_verifier ($pkceCodeVerifier)."

The url is called with the following parameters https://login.microsoftonline.com/$tenantId/oauth2/v2.0/authorize 
client_id=$applicationId
response_type=code
scope=$loginScopes
redirect_uri=$localHostRedirectUri
state=$state
code_challenge=$pkceCodeChallenge
code_challenge_method=S256

State,code_challenge & code_challenge_method can't be entered in the plugin. for some reason it is needed for me in order to login.

Also the web request https://login.microsoftonline.com/$tenantID/oauth2/v2.0/token is invoked and i can see the extra information that is provided in the Powershell script and not in the Plug in: 
state
code_verifier

some additional information: https://learn.microsoft.com/en-us/answers/questions/1381683/can-you-configure-an-app-registration-in-entra-id

Hope it is a bit more clear now 😊
