### ISSUE TITLE
http not allowed anymore

### ISSUE THREAD

**Issue by michalczerwinski** [GillesZunino/insomnia-plugin-azure-ad-authentication#2]
![image](https://user-images.githubusercontent.com/1795630/135462472-0c5e1725-3e99-4a81-b22b-0cd10b06c4f9.png)

**Comment by GillesZunino** [comment]
The plugin "insomnia-plugin-azure-ad-authentication" requires the Redirect URI to be added either under "**Mobile and Desktop applications**" or "**Web**" in Azure AD.  Single Page Applications are currently not supported. I have further emphasized this requirement in README.

As of September 30 2021, it is still possible to register under "Mobile and Desktop applications" with an http://127.0.0.1 prefix via the user interface. For "Web", Azure AD no longer allows registration of http://127.0.0.1 prefixes redirect URI in the user interface. Such redirect URIs can be registered via the manifest editor as follows:

![AzureAD-App-Manifest-RedirectUri-Registration](https://user-images.githubusercontent.com/931764/135562902-142f24c4-2218-493b-8d70-c65592dbf6ff.png)

**Comment by femo1de** [comment]
Seems like "mobile and desktop applications" now does not accept this style anymore either:

![image](https://github.com/user-attachments/assets/80ac3d62-d627-4d6c-a8a5-0e5cf4c9d927)

**Comment by GillesZunino** [comment]
Yes ! The Azure Portal does not allow http:// urls. Edit the manifest as indicated above.
