### ISSUE TITLE
Cannot select redirect URI to localhost

### ISSUE THREAD

**Issue by thepowercoders** [GillesZunino/insomnia-plugin-azure-ad-authentication#4]
The plugin errors unless it is set to http://127.0.0.1 but this is not accepted by the Azure App Registration blade which errors with "Must start with HTTPS or http://localhost message". However, the plugin does not allow the use of 'localhost'.

**Comment by nonsenseless** [comment]
I encountered this issue trying to reuse my SPA app registration. When I changed to a registration with the authentication type set to 'Mobile and desktop applications' it let me use 127.0.0.1.

**Comment by nonsenseless** [comment]
This is also mentioned in the following closed issue: https://github.com/GillesZunino/insomnia-plugin-azure-ad-authentication/issues/2
